filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/*.json
  fields_under_root: true
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "casas-%{+yyyy.MM.dd}"
  index: "ciudades-%{+yyyy.MM.dd}"

setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "ciudades-%{+2024.02.16}"
