filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/*.json
  fields_under_root: true
  json.keys_under_root: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "casas-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "casas"
setup.template.pattern: "casas-*"


# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "ciudades-%{+yyyy.MM.dd}"

